---
title: "banded_mvt"
author: "刘思洋"
date: "2024-12-04"
output: html_document
---

```{r}
rm(list = ls())
library(MASS)
library(Matrix)
library(glmnet)
library(knockoff)
library(mvtnorm)
library(hdi)
library(doParallel)
```

### FDR, power, 样本平均和样本方差的辅助函数
```{r}
analys <- function(mm, ww, q){
  ### mm: mirror statistics
  ### ww: absolute value of mirror statistics
  ### q:  FDR control level
  cutoff_set <- max(ww)
  for(t in ww){
    ps <- length(mm[mm > t])
    ng <- length(na.omit(mm[mm < -t]))
    rto <- (ng + 1)/max(ps, 1)
    if(rto <= q){
      cutoff_set <- c(cutoff_set, t)
    }
  }
  cutoff <- min(cutoff_set)
  selected_index <- which(mm > cutoff)
  
  return(selected_index)
}
### anciliary functions
fdp_power <- function(selected_index, signal_index){
  num_selected <- length(selected_index)
  tp <- length(intersect(selected_index, signal_index))
  fp <- num_selected - tp
  fdp <- fp / max(num_selected, 1)
  power <- tp / length(signal_index)
  return(list(fdp = fdp, power = power,model_size = length(selected_index), real_model_size = length(signal_index)))
}

replications <- 50
results_list <- vector("list", replications)

mean.se = function(x, ns = 1) { paste0(format(round(mean(x)*1, ns), nsmall=ns), ' (', format(round(1*sd(x)/sqrt(length(x)), ns), nsmall=ns), ')')}
```

```{r}
Signal_index <- function(Sigma_0) {
  # Set lower triangular elements to 0
  Sig_0_upper <- Sigma_0
  Sig_0_upper[lower.tri(Sig_0_upper)] <- 0
  # Extract upper triangular elements, arranged by row
  upper_tri_vector <- Sig_0_upper[upper.tri(Sig_0_upper, diag = TRUE)]
  # Get indices of non-zero elements
  signal_index <- which(upper_tri_vector != 0)
  
  return(signal_index)
}
```

### Generate data
```{r}
# Function to generate A1 matrix (banded covariance matrix)
A_1_sigma <- function(p) {
  matrix <- matrix(0, nrow = p, ncol = p)
  for (i in 1:p) {
    for (j in 1:p) {
      matrix[i, j] <- max(0, 1 - abs(i - j) / 10)  # (1-rou^|i-j|/h), h=10,20,50, or rou(0,1), or p, n varaiance, (p<n)
    }
  }
  
  return(matrix)
}

A_2_sigma <- function(p) {
  matrix <- diag(4, p, p)
  return(matrix)
}

sigma_0 <- function(p) {
  A1 <- A_1_sigma(p / 2)  
  A2 <- A_2_sigma(p / 2)
  
  # Full block diagonal matrix Sigma_0
  sigma_0 <- matrix(0, nrow = p, ncol = p)
  sigma_0[1:(p/2), 1:(p/2)] <- A1
  sigma_0[(p/2+1):p, (p/2+1):p] <- A2
  return(sigma_0)
}
```

### data-splitting methods (DS and MDS)(mle)
```{r}
DS <- function(X, num_split, q){
  n <- dim(X)[1]; p <- dim(X)[2]
  num_upper_tri_elements <- p * (p + 1) / 2
  inclusion_rate <- matrix(0, nrow = num_split, ncol = num_upper_tri_elements)
 # inclusion_rate <- matrix(0, nrow = num_split, ncol = p)
  fdp <- rep(0, num_split)
  power <- rep(0, num_split)
  num_select <- rep(0, num_split)
  
  for(iter in 1:num_split){
    ### randomly split the data
    sample_index1 <- sample(x = c(1:n), size = 0.5 * n, replace = F)
    sample_index2 <- setdiff(c(1:n), sample_index1)
    
    ### get mle on the first half of data
    S  = cov(X[sample_index1, ])               
    mu_mle  = colMeans(X[sample_index1, ])    
    Sig_mle = (n-1)*S/n      
    Sig_mle_upper <- Sig_mle
    Sig_mle_upper[lower.tri(Sig_mle_upper)] <- 0  # Set lower triangular elements to 0
    # Extract non-zero values by row and arrange them as a vector
    upper_tri_vector <- Sig_mle_upper[upper.tri(Sig_mle_upper, diag = TRUE)]
    beta1 <- upper_tri_vector
    nonzero_index <- which(beta1 != 0)
    if(length(nonzero_index)!=0){ 
    
    ### get mle on the second half of data
    S  = cov(X[sample_index2, ])               
    mu_mle  = colMeans(X[sample_index2, ])    
    Sig_mle = (n-1)*S/n      
    Sig_mle_upper <- Sig_mle
    Sig_mle_upper[lower.tri(Sig_mle_upper)] <- 0  # Set lower triangular elements to 0
    # Extract non-zero values by row and arrange them as a vector
    upper_tri_vector <- Sig_mle_upper[upper.tri(Sig_mle_upper, diag = TRUE)]
    beta2 <- upper_tri_vector
    
    ### calculate the mirror statistics
      M <- sign(beta1 * beta2) * (abs(beta1) + abs(beta2))
      # M <- abs(beta1 + beta2) - abs(beta1 - beta2)
      DS_selected_index <- analys(M, abs(M), q)
      
      ### number of selected variables
      if(length(DS_selected_index)!=0){
        num_select[iter] <- length(DS_selected_index)
        inclusion_rate[iter, DS_selected_index] <- 1/num_select[iter]
        
        ### calculate fdp and power
        result <- fdp_power(DS_selected_index, signal_index)
        fdp[iter] <- result$fdp
        power[iter] <- result$power
      }
    }
  }
  
  ### single data-splitting (DS) result
  DS_fdp <- fdp[1]
  DS_power <- power[1]
  
  ### multiple data-splitting (MDS) result
  inclusion_rate <- apply(inclusion_rate, 2, mean)
  
  ### rank the features by the empirical inclusion rate
  feature_rank <- order(inclusion_rate)
  feature_rank <- setdiff(feature_rank, which(inclusion_rate == 0))
  if(length(feature_rank)!=0){
    null_feature <- numeric()
    
    ### backtracking 
    for(feature_index in 1:length(feature_rank)){
      if(sum(inclusion_rate[feature_rank[1:feature_index]]) > q){
        break
      }else{
        null_feature <- c(null_feature, feature_rank[feature_index])
      }
    }
    MDS_selected_index <- setdiff(feature_rank, null_feature)
    
    ### calculate fdp and power
    result <- fdp_power(MDS_selected_index, signal_index)
    MDS_fdp <- result$fdp
    MDS_power <- result$power
  }
   else{
    MDS_fdp <- 0
    MDS_power <- 0
  }
  return(list(DS_fdp = DS_fdp, DS_power = DS_power, MDS_fdp = MDS_fdp, MDS_power = MDS_power, DS_model_size = length(DS_selected_index), MDS_model_size = length(MDS_selected_index), real_model_size = length(signal_index)))
 }
```
### structure 2 is multi-block-banded
```{r}
sigma_0 <- function(p, block_size = 5, rho = 0.8) {
  Sigma <- matrix(0, nrow = p, ncol = p)
  # Set the diagonal with random variances
  diag(Sigma) <- runif(p, min = 0.8, max = 2)
  # Determine the number of full blocks
  num_blocks <- floor(p / block_size)
  # Assign block memberships
  # Any leftover rows/columns beyond the last full block get a block membership of 0
  block_membership <- c(
    rep(seq_len(num_blocks), each = block_size),
    rep(0, p - num_blocks * block_size)
  )
  # Create a logical matrix that identifies elements within the same nonzero block
  same_block_matrix <- outer(block_membership, block_membership, 
                             FUN = function(x, y) (x == y) & (x != 0))
  # Identify off-diagonal positions within the same block
  off_diag_same_block <- same_block_matrix & (row(Sigma) != col(Sigma))
  # Set off-diagonal elements within these blocks to rho
  Sigma[off_diag_same_block] <- rho

  return(Sigma)
}
```
### p=10, n=300
```{r}
p <- 10 
n <- 300 
Sigma_0 <- sigma_0(p)
mean_vector <- rep(0, p)
set.seed(2024)
for (i in 1:replications) {
  X <- rmvt(n = n, delta = mean_vector, sigma = Sigma_0, df = 5, type = "shifted")
  signal_index <- Signal_index(Sigma_0)
  results_list[[i]] <- DS(X, 50, 0.1)
}
elements <- names(results_list[[1]])
empirical_results <- sapply(elements, function(element) {
  values <- sapply(results_list, function(res) res[[element]])
  mean.se(values, ns = 2)
})

empirical_results
```
### p=50, n=300
```{r}
p <- 50
n <- 300 
Sigma_0 <- sigma_0(p)
mean_vector <- rep(0, p)
set.seed(2024)
for (i in 1:replications) {
  X <- rmvt(n = n, delta = mean_vector, sigma = Sigma_0, df = 5, type = "shifted")
  signal_index <- Signal_index(Sigma_0)
  results_list[[i]] <- DS(X, 50, 0.1)
}
elements <- names(results_list[[1]])
empirical_results <- sapply(elements, function(element) {
  values <- sapply(results_list, function(res) res[[element]])
  mean.se(values, ns = 2)
})

empirical_results
```
### p=100, n=300
```{r}
p <- 100 
n <- 300 
Sigma_0 <- sigma_0(p)
mean_vector <- rep(0, p)
set.seed(2024)
for (i in 1:replications) {
  X <- rmvt(n = n, delta = mean_vector, sigma = Sigma_0, df = 5, type = "shifted")
  signal_index <- Signal_index(Sigma_0)
  results_list[[i]] <- DS(X, 50, 0.1)
}
elements <- names(results_list[[1]])
empirical_results <- sapply(elements, function(element) {
  values <- sapply(results_list, function(res) res[[element]])
  mean.se(values, ns = 2)
})

empirical_results
```
### p=200, n=300
```{r}
p <- 200 
n <- 300 
Sigma_0 <- sigma_0(p)
mean_vector <- rep(0, p)
set.seed(2024)
for (i in 1:replications) {
  X <- rmvt(n = n, delta = mean_vector, sigma = Sigma_0, df = 5, type = "shifted")
  signal_index <- Signal_index(Sigma_0)
  results_list[[i]] <- DS(X, 50, 0.1)
}
elements <- names(results_list[[1]])
empirical_results <- sapply(elements, function(element) {
  values <- sapply(results_list, function(res) res[[element]])
  mean.se(values, ns = 2)
})

empirical_results
```

### p=300, n=300
```{r}
p <- 300 
n <- 300 
Sigma_0 <- sigma_0(p)
mean_vector <- rep(0, p)
set.seed(2024)
for (i in 1:replications) {
  X <- rmvt(n = n, delta = mean_vector, sigma = Sigma_0, df = 5, type = "shifted")
  signal_index <- Signal_index(Sigma_0)
  results_list[[i]] <- DS(X, 50, 0.1)
}
elements <- names(results_list[[1]])
empirical_results <- sapply(elements, function(element) {
  values <- sapply(results_list, function(res) res[[element]])
  mean.se(values, ns = 2)
})

empirical_results
```
